# This is a config for E2B sandbox template.
# You can use template ID (3l40u2axv4g0lszgq1z1) or template name (vibe-nextjs-test-2222) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-2222") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-2222") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-2222')

team_id = "fc5d333b-ef5b-465e-a022-8b8e2eede6e3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-2222"
template_id = "3l40u2axv4g0lszgq1z1"
